jobs:
  - job: build_and_run_ut_by_linux
    displayName: Build and Run Unit Test By (Ubuntu:Latest)
    timeoutInMinutes: 120
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DockerCompose@0
        displayName: "Deploy Docker Compose"
        inputs:
          action: 'Run a Docker Compose command'
          containerregistrytype: 'Container Registry'
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
          dockerComposeFileArgs: |
            workDirectory=$(Build.SourcesDirectory)
          dockerComposeCommand: up -d
      - task: UseDotNet@2
        displayName: "Install .NET Core SDK"
        inputs:
          version: 5.0.100
      - task: UseDotNet@2
        displayName: "Install .NET Core SDK"
        inputs:
          version: 3.1.403
      - script: bash scripts/build.sh
        displayName: "Build"
      - script: bash scripts/test.sh
        displayName: "Run Unit Test"
      - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
        displayName: ReportGenerator
        inputs:
          reports: "$(Build.SourcesDirectory)/test/Unit/*/TestResults/*/coverage.cobertura.xml"
          targetdir: "$(Build.SourcesDirectory)/CodeCoverage"
          reporttypes: "Cobertura"
          assemblyfilters: "-xunit*"
      - script: bash <(curl -s https://codecov.io/bash)
        displayName: "Upload to codecov.io"
      - task: DockerCompose@0
        displayName : "Down Docker Compose"
        inputs:
          action: 'Run a Docker Compose command'
          containerregistrytype: 'Container Registry'
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
          dockerComposeFileArgs: |
            workDirectory=$(Build.SourcesDirectory)
          dockerComposeCommand: down --remove-orphans
