name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300

      - name: Test And Coverage Report 📝
        run: |
          dotnet build
          dotnet test --collect:"XPlat Code Coverage"
          find ./test/hiredis.tests -name "coverage.cobertura.xml" -type f -exec cp {} ./ \;
          bash <(curl -s https://codecov.io/bash) -Z -f coverage.cobertura.xml -t $CODECOV_TOKEN
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}